### ISSUE TITLE
Short term TODO

### ISSUE THREAD

**Issue by ottojo** [ToolboxPlane/FlightControllerBoard#9]
- [x] BNO INT Pin on ATMega
- [x] Verify FT230X Schematic matches "Bus Powered" reference implementation
- [x] Verify Pullups on UARTs
- [ ] Eval LMZ21700SILR

**Comment by aul12** [comment]
- [x] Reset Button
- [x] Move LEDs to Register L
